1.Create a class Employee and then do the following:

• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [1]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Sai Ram", "Uppalapati", 100000, "Manager")
employee2 = Employee("Venkat", "Uppalapati", 90000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Madhavi", "Uppalapati", 75000, "Finance")
fulltime_employee2 = FulltimeEmployee("Nandhu", "Nandini", 60000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)



Average Salary for Employees: 47500.0
Average Salary for Fulltime Employees: 33750.0


2.Numpy

Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)

In [2]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [ 2.55273685  7.59333718  6.32741269 16.7248906  17.95685087 19.47524646
 13.80332948  4.78615567 14.35406497  3.6498996   3.58871339  3.59389651
  7.3425797  13.43955299 15.7967192  13.09130919 15.42377339 18.92089029
  3.75404771  3.79369691]


In [3]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[ 2.55273685  7.59333718  6.32741269 16.7248906  17.95685087]
 [19.47524646 13.80332948  4.78615567 14.35406497  3.6498996 ]
 [ 3.58871339  3.59389651  7.3425797  13.43955299 15.7967192 ]
 [13.09130919 15.42377339 18.92089029  3.75404771  3.79369691]]


In [4]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 2.55273685  7.59333718  6.32741269 16.7248906   0.        ]
 [ 0.         13.80332948  4.78615567 14.35406497  3.6498996 ]
 [ 3.58871339  3.59389651  7.3425797  13.43955299  0.        ]
 [13.09130919 15.42377339  0.          3.75404771  3.79369691]]
